### ISSUE TITLE
[Bug] Mobile : explorer doesn't match light color

### ISSUE THREAD

**Issue by Mara-Li** [ZaherAlMajed/Illusion-Theme.md#3]
This theme is very neat! But I have a problem on mobile : ![image](https://user-images.githubusercontent.com/30244939/125854228-43d3d7c6-b460-4d7d-8c95-1869a1edf63a.png)

I'm on IOS 14. Because of that I can't check the CSS. Maybe a CSS master can help?

**Comment by ZaherAlMajed** [comment]
Will be working on this for the next release, thanks :)
